[package]
name = "tld"
version = "0.4.0"
authors = ["Ernestas Poskus <ernestas.poskus@gmail.com>"]
license = "BSD-3-Clause"
documentation = "https://github.com/linkosmos/tld"
homepage = "https://github.com/linkosmos/tld"
repository = "https://github.com/linkosmos/tld"
description = """
Top Level domain static hash map for Rust according to list of iana.org
"""

[dependencies]
phf = "0.7.21"
phf_macros = "0.7.21"