[package]
authors = ["Ernestas Poskus <ernestas.poskus@gmail.com>"]
description = """
Top Level domain static hash map for Rust according to list of iana.org
"""
documentation = "https://docs.rs/tld"
homepage = "https://github.com/linkosmos/tld"
license = "BSD-3-Clause"
name = "tld"
repository = "https://github.com/linkosmos/tld"
version = "1.18.0"

[dependencies]
phf = "0.7.24"
phf_macros = "0.7.24"
